version: '3'

services:
  app:
    build: .
    environment:
      - NODE_ENV=test
      - BUILDKITE
      - BUILDKITE_AGENT_ID
      - BUILDKITE_AGENT_META_DATA_AWS_AMI_ID
      - BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_ID
      - BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE
      - BUILDKITE_AGENT_META_DATA_BUILDKITE_AWS_STACK
      - BUILDKITE_AGENT_META_DATA_DOCKER
      - BUILDKITE_AGENT_META_DATA_QUEUE
      - BUILDKITE_AGENT_META_DATA_STACK
      - BUILDKITE_AGENT_NAME
      - BUILDKITE_ARTIFACT_PATHS
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_CHECKOUT_PATH
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMAND
      - BUILDKITE_COMMIT
      - BUILDKITE_JEST_ANALYTICS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_ORGANIZATION_SLUG
      - BUILDKITE_PIPELINE_DEFAULT_BRANCH
      - BUILDKITE_PIPELINE_PROVIDER
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_REPO
      - BUILDKITE_REPO
      - BUILDKITE_REPO_SSH_HOST
      - BUILDKITE_RETRY_COUNT
      - BUILDKITE_SCRIPT_PATH
      - BUILDKITE_SOURCE
      - BUILDKITE_STEP_ID
      - BUILDKITE_TAG
      - BUILDKITE_TIMEOUT
