steps:
  - label: ":jest: jest"
    commands:
      - "apk add  --no-cache --virtual .gyp python3 make g++"
      - "yarn install"
      - "yarn test"
    plugins:
      - docker#v3.8.0:
          image: "node:14-alpine"
